// Re-exports the event schemas and the shared decisions so other packages can import them from @apm/shared.
export { evidenceRowChars, JSON_BODY_LIMIT_BYTES, SCHEMA_VERSION } from "./schema/events.js";
export {
  eventDetailsSchema,
  eventSourceSchema,
  eventSources,
  normalizedEventSchema,
  sessionMessageSchema,
} from "./schema/events.js";
export type { EventDetails, EventSource, NormalizedEvent, SessionMessage } from "./schema/events.js";
export { evaluateSessionEligibility } from "./logic/session-eligibility.js";
export type { ExclusionReason, SessionEligibility } from "./logic/session-eligibility.js";
export { folderMatchesRoot, matchingRoot, normalizeAbsolutePath } from "./logic/selected-folders.js";
// sessionContentEventId is @apm/shared/session-content-id. It uses node:crypto, which the browser cannot load.
export {
  acceptedInvitationSchema,
  basisSchema,
  createdInvitationSchema,
  pairingCodeSchema,
  connectedProjectSchema,
  connectProjectResponseSchema,
  contributorsSchema,
  correctionResultSchema,
  correctionSchema,
  evidenceDetailSchema,
  featureDetailSchema,
  featureResponseSchema,
  graphFeatureSchema,
  graphRevisionSchema,
  graphSchema,
  graphWorkItemSchema,
  historyEntrySchema,
  layoutSchema,
  meSchema,
  modelCredentialSchema,
  modelProviderIdSchema,
  modelProviderIds,
  modelSetupSchema,
  nodePositionSchema,
  projectListSchema,
  projectSchema,
  projectSettingsSchema,
  pullRequestDetailSchema,
  relationshipSchema,
  roleSchema,
  savedLayoutSchema,
  supplierModelListSchema,
  supplierModelSchema,
  workItemDetailSchema,
  workItemResponseSchema,
  workItemStateSchema,
  workItemStates,
} from "./schema/api.js";
export type {
  Basis,
  Contributors,
  Correction,
  EvidenceDetail,
  FeatureDetail,
  Graph,
  GraphFeature,
  GraphRevision,
  GraphWorkItem,
  HistoryEntry,
  Me,
  ModelCredential,
  ModelProviderId,
  ModelSetup,
  NodePosition,
  PendingInvitation,
  Project,
  ProjectSettings,
  PullRequestDetail,
  Relationship,
  Role,
  SupplierModel,
  WorkItemDetail,
  WorkItemState,
  WorkflowRun,
} from "./schema/api.js";
